### ISSUE TITLE
Skillページ以外でもスクロールイベントが発生してしまっている

### ISSUE THREAD

**Issue by fumihiko-hidaka** [ymdman/portfolio-2018#1]
https://github.com/ymdman/portfolio-2018/blob/315830d2d72e0d30fc90f4fa70accdf2ec348232/src/components/SkillGraph/SkillGraph.js#L39

componentDidMountでaddEventListenerするのはいいと思うんですけれども、
componentWillUnmountで消さないとダメじゃないです？

**Comment by ymdman** [comment]
ご指摘ありがとうございます！
仰られる通りです。
